version: '3.3'
services:
   locator-form-frontend:
      image: locator-form
      build:
         context: ./locator-form-frontend
         dockerfile: ./Dockerfile.prod
      depends_on:
         - locator-form.openelis.org
      restart: always
      ports:
         - 80:80
         - 443:443
      secrets:
         -  source: client_facing_cert
         -  source: client_facing_key
         -  source: client_facing_key_pass
      
   locator-form.openelis.org:
      image: locator-form-webapp
      build:
         context: ./locator-form-webapp
         dockerfile: docker/docker-build/Dockerfile
      restart: always
      ports:
         - 8449:8443
      extra_hosts:
         - infohighway.govmu.org:192.168.6.91
      volumes:
         - ./prod/properties/locatorform-app.properties:/var/lib/locatorform/app.properties
      secrets:
         -  source: client_facing_keystore
         -  source: keystore
         -  source: truststore
         
   hapi-fhir-jpaserver:
      container_name: lf-hapi-fhir-jpaserver
      image: hapiproject/hapi:latest
      restart: always
      ports:
         - 8448:8443
      volumes:
         - ./prod/tomcat/hapi_server.xml:/usr/local/tomcat/conf/server.xml
      environment: 
        SPRING_CONFIG_LOCATION: file:///run/secrets/application.yaml
      secrets:
         -  source: application.yaml
         -  source: keystore
         -  source: truststore
       
secrets:
   application.yaml:
      file: ./prod/properties/application.yaml
   client_facing_keystore:
      file: ./prod/ssl/client_facing_openelis.org.keystore
   client_facing_cert:
      file: ./prod/ssl/client_facing_openelis.org.crt
   client_facing_key:
      file: ./prod/ssl/client_facing_openelis.org.key
   client_facing_key_pass:
      file: ./prod/ssl/client_facing_openelis.org.key_pass
   truststore:
      file: ./prod/ssl/openelis.org.truststore
   keystore:
      file: ./prod/ssl/openelis.org.keystore
   cert:
      file: ./prod/ssl/openelis.org.crt
   key:
      file: ./prod/ssl/openelis.org.key
   key_pass:
      file: ./prod/ssl/openelis.org.key_pass
